# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFirsttest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_firsttest(self):
    self.driver.get("http://selenium1py.pythonanywhere.com/ru/")
    self.driver.set_window_size(1090, 684)
    self.driver.find_element(By.ID, "login_link").click()
    self.driver.find_element(By.ID, "id_login-username").click()
    self.driver.find_element(By.ID, "id_login-username").send_keys("starodubtseva_test@test.tst")
    self.driver.find_element(By.ID, "login_form").click()
    self.driver.find_element(By.ID, "id_login-password").click()
    self.driver.find_element(By.ID, "id_login-password").send_keys("mjnhbg1357")
    self.driver.find_element(By.ID, "id_login-password").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "login_submit").click()
    self.driver.find_element(By.ID, "logout_link").click()
  
